name: pcl
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info: ^2.0.2
  shared_preferences: ^2.2.2
  flutter_login: ^4.2.1
  flutter_typeahead: ^4.8.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  lottie: ^2.6.0
  intl: ^0.18.0
  image_picker: ^1.0.7
  multi_image_picker: ^4.8.01
  path_provider: ^2.1.2
  reactive_date_time_picker: ^3.0.0
  flutter_signature_pad: ^3.0.1
  connectivity: ^3.0.6
  timeline_tile: ^2.0.0
  reactive_forms: ^16.1.1
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  onesignal_flutter: ^5.1.0
  navbar_router: ^0.7.3
  salomon_bottom_bar: ^3.3.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - assets/images/logo-dark.png
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"